### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [piccobit/aperiodic-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with a license since some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

**Comment by piccobit** [comment]
@unixorn - Hi, thanks for pointing me to the missing license. I've added a license file containing the MIT license to the repository. Any other points I've to watch for?

**Comment by piccobit** [comment]
@unixorn - FYI, I've also extended the README.md and added a screenshot.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/760, thanks
